### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by difnicolas** [AppWrenchStudios/AppWrenchStudios.github.io#2]
Write the html for the home page. When landing on page load landing pages search into search result list, if no search, leaving result field blank. (Communicate with Daphne so she knows how to pass search term to you. Communicate with DB for information regarding search results). Home page also includes Log-In / Sign-Up modal, communicate with Nicolas for this portion.

**Comment by nigelg11861** [comment]
Moved to correct repo (renamed Search Results Pg).
