### ISSUE TITLE
Log-in / Sign-up Modal

### ISSUE THREAD

**Issue by difnicolas** [AppWrenchStudios/AppWrenchStudios.github.io#3]
Create the Modal to handle logging in, while in the same modal, create a tab system that allows users to register at the same time. When finished registering, link consumers to search, and stores to account page. (Communicate with Nigel for adding this functionality to the homepage, and Communicate with Daphne for adding this functionality to Landing Page).

**Comment by nigelg11861** [comment]
Moved to correct repo.
